### ISSUE TITLE
problems using imagesloaded with browserify and jquery

### ISSUE THREAD

**Issue by peillis** [desandro/imagesloaded#180]
Suppose you have a script with an isolated jquery (v2.1.3) that you require with browserify, and the page has another jquery (v.1.4.4), then if you use imagesloaded in the browserify script you get an error: TypeError: undefined is not a function, because imagesloaded is getting $ as the jquery 1.4.4 and not the required with browserify, which it should.

**Comment by desandro** [comment]
I'm afraid there is not an easy solution here. imagesLoaded will work with jQuery 1.7+. If you are using a duplicate jQuery v1.4.4, which is four years old, then it will break. Moreover, `$.fn.imagesLoaded` will not have promises, which is bad. So I'd rather imagesLoaded break, then try to degrade silently and not alert you that promises will be broken.

I would try to resolve that duplicate old jQuery, rather than catching this edge case with imagesLoaded.

**Comment by olsonpm** [comment]
@desandro: isn't the root problem that this library looks at the window's jquery object as opposed to either requiring it directly or taking it in as a parameter?  I'm just resolving this issue for a personal project now and those are the two solutions I'm aware of.

**Comment by desandro** [comment]
I need to update docs with example of using browserify + jquery + imagesLoaded. Similar to Masonry http://masonry.desandro.com/appendix.html#browserify

**Comment by olsonpm** [comment]
Ah - that's another solution.

**Comment by desandro** [comment]
I've added docs on Browserify + imagesLoaded http://imagesloaded.desandro.com/#browserify

imagesLoaded v3.2.0 adds the `.makeJQueryPlugin()` utility method.

``` js
var $ = require('jquery');
var imagesLoaded = require('imagesloaded');

// provide jQuery argument
imagesLoaded.makeJQueryPlugin( $ );
// now use .imagesLoaded() jQuery plugin
$('#container').imagesLoaded( function() {...});
```

**Comment by desandro** [comment]
I'm closing this issue as resolved. If you run into an issue with imagesLoaded, Browserify or `makeJQueryPlugin`, please open a new issue.
